Asp.net_GraphQL/Models/ErrorViewModel.cs
namespace Asp.net_GraphQL.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Asp.net_GraphQL/Controllers/FlowerBouquetsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Asp.net_GraphQL.DataAccess;
using Asp.net_GraphQL.Service;


namespace Asp.net_GraphQL.Controllers
{
    public class FlowerBouquetsController : Controller
    {
        private FUFlowerBouquetManagementContext _context;
        private IRepository<FlowerBouquet> Generic;
        private QueryType QueryType;

        public FlowerBouquetsController(FUFlowerBouquetManagementContext context, QueryType queryType)
        {
            this._context = context;
            this.Generic = new Repository<FlowerBouquet>(context);
            this.QueryType = queryType;
        }

        public async Task<IActionResult> Index()
        {
            var fUFlowerBouquetManagementContext = QueryType.AllCakesAsync(_context);
            return View( fUFlowerBouquetManagementContext);
        }

        // GET: FlowerBouquets/Details/5
        public async Task<IActionResult> Details(int? id)
        {


            var flowerBouquet = await Generic.GetByIdAsync(id);
            if (flowerBouquet == null)
            {
                return NotFound();
            }

            return View(flowerBouquet);
        }

        // GET: FlowerBouquets/Create
        public async Task<IActionResult> Create()
        {
            IEnumerable<FlowerBouquet> fu =  Generic.GetAll();
            var uniqueCategories = fu.Select(f => f.Category).Distinct();
            var uniqueSuppliers = fu.Select(f => f.Supplier).Distinct();
            ViewData["CategoryId"] = new SelectList(uniqueCategories, "CategoryId", "CategoryId");
            ViewData["SupplierId"] = new SelectList(uniqueSuppliers, "SupplierId", "SupplierId");
            return View();
        }





        // POST: FlowerBouquets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FlowerBouquetId,CategoryId,FlowerBouquetName,Description,UnitPrice,UnitsInStock,FlowerBouquetStatus,SupplierId")] FlowerBouquet flowerBouquet)
        {
            if (ModelState.IsValid)
            {
               Generic.InsertAsync(flowerBouquet);
           
                return RedirectToAction(nameof(Index));
            }
            IEnumerable<FlowerBouquet> fu =  Generic.GetAll();
            var uniqueCategories = fu.Select(f => f.Category).Distinct();
            var uniqueSuppliers = fu.Select(f => f.Supplier).Distinct();
            ViewData["CategoryId"] = new SelectList(uniqueCategories, "CategoryId", "CategoryId");
            ViewData["SupplierId"] = new SelectList(uniqueSuppliers, "SupplierId", "SupplierId");
            return View(flowerBouquet);
        }

        // GET: FlowerBouquets/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || Generic.GetByIdAsync(id) == null)
            {
                return NotFound();
            }

            var flowerBouquet = await Generic.GetByIdAsync(id);
            if (flowerBouquet == null)
            {
                return NotFound();
            }
            IEnumerable<FlowerBouquet> fu =  Generic.GetAll();
            var uniqueCategories = fu.Select(f => f.Category).Distinct();
            var uniqueSuppliers = fu.Select(f => f.Supplier).Distinct();
            ViewData["CategoryId"] = new SelectList(uniqueCategories, "CategoryId", "CategoryId");
            ViewData["SupplierId"] = new SelectList(uniqueSuppliers, "SupplierId", "SupplierId");
            return View(flowerBouquet);
        }

        // POST: FlowerBouquets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FlowerBouquetId,CategoryId,FlowerBouquetName,Description,UnitPrice,UnitsInStock,FlowerBouquetStatus,SupplierId")] FlowerBouquet flowerBouquet)
        {
            if (id != flowerBouquet.FlowerBouquetId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    Generic.UpdateAsync(flowerBouquet);
                 
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (Generic.GetByIdAsync(id) ==null)
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            IEnumerable<FlowerBouquet> fu =  Generic.GetAll();
            var uniqueCategories = fu.Select(f => f.Category).Distinct();
            var uniqueSuppliers = fu.Select(f => f.Supplier).Distinct();
            ViewData["CategoryId"] = new SelectList(uniqueCategories, "CategoryId", "CategoryId");
            ViewData["SupplierId"] = new SelectList(uniqueSuppliers, "SupplierId", "SupplierId");
            return View(flowerBouquet);
        }

        // GET: FlowerBouquets/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null )
            {
                return NotFound();
            }

           var search = Generic.GetByIdAsync(id);

            return View(search);
        }

        // POST: FlowerBouquets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            Generic.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

    
    }
}

Asp.net_GraphQL/Controllers/HomeController.cs
using Asp.net_GraphQL.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Asp.net_GraphQL.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Asp.net_GraphQL/Views/FlowerBouquets/Create.cshtml
@model Asp.net_GraphQL.DataAccess.FlowerBouquet

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>FlowerBouquet</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FlowerBouquetId" class="control-label"></label>
                <input asp-for="FlowerBouquetId" class="form-control" />
                <span asp-validation-for="FlowerBouquetId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class ="form-control" asp-items="ViewBag.CategoryId"></select>
            </div>
            <div class="form-group">
                <label asp-for="FlowerBouquetName" class="control-label"></label>
                <input asp-for="FlowerBouquetName" class="form-control" />
                <span asp-validation-for="FlowerBouquetName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UnitPrice" class="control-label"></label>
                <input asp-for="UnitPrice" class="form-control" />
                <span asp-validation-for="UnitPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UnitsInStock" class="control-label"></label>
                <input asp-for="UnitsInStock" class="form-control" />
                <span asp-validation-for="UnitsInStock" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FlowerBouquetStatus" class="control-label"></label>
                <input asp-for="FlowerBouquetStatus" class="form-control" />
                <span asp-validation-for="FlowerBouquetStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SupplierId" class="control-label"></label>
                <select asp-for="SupplierId" class ="form-control" asp-items="ViewBag.SupplierId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Asp.net_GraphQL/Views/FlowerBouquets/Delete.cshtml
@model Asp.net_GraphQL.DataAccess.FlowerBouquet

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>FlowerBouquet</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FlowerBouquetName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FlowerBouquetName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UnitPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UnitPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UnitsInStock)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UnitsInStock)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FlowerBouquetStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FlowerBouquetStatus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.CategoryId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Supplier)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Supplier.SupplierId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="FlowerBouquetId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Asp.net_GraphQL/Views/FlowerBouquets/Details.cshtml
@model Asp.net_GraphQL.DataAccess.FlowerBouquet

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>FlowerBouquet</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FlowerBouquetName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FlowerBouquetName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UnitPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UnitPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UnitsInStock)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UnitsInStock)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FlowerBouquetStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FlowerBouquetStatus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.CategoryId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Supplier)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Supplier.SupplierId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.FlowerBouquetId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Asp.net_GraphQL/Views/FlowerBouquets/Edit.cshtml
@model Asp.net_GraphQL.DataAccess.FlowerBouquet

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>FlowerBouquet</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="FlowerBouquetId" />
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FlowerBouquetName" class="control-label"></label>
                <input asp-for="FlowerBouquetName" class="form-control" />
                <span asp-validation-for="FlowerBouquetName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UnitPrice" class="control-label"></label>
                <input asp-for="UnitPrice" class="form-control" />
                <span asp-validation-for="UnitPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UnitsInStock" class="control-label"></label>
                <input asp-for="UnitsInStock" class="form-control" />
                <span asp-validation-for="UnitsInStock" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FlowerBouquetStatus" class="control-label"></label>
                <input asp-for="FlowerBouquetStatus" class="form-control" />
                <span asp-validation-for="FlowerBouquetStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SupplierId" class="control-label"></label>
                <select asp-for="SupplierId" class="form-control" asp-items="ViewBag.SupplierId"></select>
                <span asp-validation-for="SupplierId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Asp.net_GraphQL/Views/FlowerBouquets/Index.cshtml
@model IEnumerable<Asp.net_GraphQL.DataAccess.FlowerBouquet>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FlowerBouquetName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UnitPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UnitsInStock)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FlowerBouquetStatus)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Supplier)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FlowerBouquetName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UnitPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UnitsInStock)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FlowerBouquetStatus)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category.CategoryId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Supplier.SupplierId)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.FlowerBouquetId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.FlowerBouquetId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.FlowerBouquetId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Asp.net_GraphQL/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Asp.net_GraphQL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Asp.net_GraphQL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Asp.net_GraphQL.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Asp.net_GraphQL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FlowerBouquets" asp-action="Index">Home</a>
                        </li>                                                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Asp.net_GraphQL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>